<?php
    $this->layout('application.phtml', [
        'title' => _('Add a domain to monitor'),
        'navigation_active' => 'domains',
    ]);
?>

<h1><?= _('Add a domain to monitor') ?></h1>

<form method="post" action="<?= url('create domain') ?>">
    <?php if ($error): ?>
        <p class="form__error">
            <?= $error ?>
        </p>
    <?php endif; ?>

    <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />

    <div class="form-group <?= isset($errors['id']) ? 'form-group--invalid' : '' ?>">
        <label for="id">
            <?= _('Domain name') ?>
        </label>

        <input
            id="id"
            name="id"
            type="text"
            value="<?= $id ?>"
            required
            autofocus
        />

        <?php if (isset($errors['id'])): ?>
            <p class="form-group__error">
                <?= $errors['id'] ?>
            </p>
        <?php endif; ?>
    </div>

    <div class="form__actions">
        <button type="submit" class="button--primary">
            <?= _('Monitor the domain') ?>
        </button>

        <a href="<?= url('domains') ?>">
            <?= _('Back to the domains') ?>
        </a>
    </div>
</form>
