<?php
    $this->layout('application.phtml', [
        'title' => _('Add a domain to monitor'),
        'navigation_active' => 'domains',
    ]);
?>

<h1><?= _('Add a domain to monitor') ?></h1>

<form method="post" action="<?= url('create domain') ?>">
    <?php if ($form->isInvalid('@base')): ?>
        <p class="form__error">
            <?= $form->error('@base') ?>
        </p>
    <?php endif; ?>

    <div class="form-group <?= $form->isInvalid('id') ? 'form-group--invalid' : '' ?>">
        <label for="id">
            <?= _('Domain name') ?>
        </label>

        <input
            id="id"
            name="id"
            type="text"
            value="<?= $form->id ?>"
            required
            autofocus
        />

        <?php if ($form->isInvalid('id')): ?>
            <p class="form-group__error">
                <?= $form->error('id') ?>
            </p>
        <?php endif; ?>
    </div>

    <div class="form__actions">
        <button type="submit" class="button--primary">
            <?= _('Monitor the domain') ?>
        </button>

        <a href="<?= url('domains') ?>">
            <?= _('Back to the domains') ?>
        </a>
    </div>

    <input type="hidden" name="csrf_token" value="<?= $form->csrfToken() ?>">
</form>
