<?php $this->layout('base.phtml', ['title' => _f('Domain %s', $this->protect($domain->id))]); ?>

<h1><?= $this->protect($domain->id) ?></h1>

<form method="post" action="<?= url('delete domain', ['id' => $domain->id]) ?>">
    <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
    <button type="submit" class="button--ghost">
        <?= _('Delete domain') ?>
    </button>
</form>

<p>
    <?= _f('Status: %s', _($domain->status())) ?>
    <?php if ($last_heartbeat): ?>
        /
        <?= _f('Last check: %s', $last_heartbeat['created_at']) ?>
    <?php endif; ?>
</p>

<?php if ($alarms): ?>
    <h2><?= _('Alarms') ?></h2>

    <ul>
        <?php foreach ($alarms as $alarm): ?>
            <li>
                <?= $alarm['created_at'] ?>
                <?php if ($alarm['finished_at']): ?>
                    (<?= _('finished') ?>)
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
