<?php
    $this->layout('application.phtml', [
        'title' => _f('Domain %s', $this->protect($domain->id)),
        'navigation_active' => 'domains',
    ]);
?>

<h1>
    <a target="_blank" rel="noopener noreferrer" href="https://<?= $this->protect($domain->id) ?>">
        <?= $this->protect($domain->id) ?>
    </a>
</h1>

<?php if ($domain->status() === 'up'): ?>
    <p class="paragraph--featured paragraph--success">
        <?= _('Status: up 😊') ?>
    </p>
<?php elseif ($domain->status() === 'down'): ?>
    <p class="paragraph--featured paragraph--alert">
        <?= _('Status: down 😫') ?>
    </p>
<?php else: ?>
    <p class="paragraph--featured paragraph--warning">
        <?= _('Status: unknown 😵') ?>
    </p>
<?php endif; ?>

<?php if ($last_heartbeat_at): ?>
    <p class="paragraph--centered paragraph--muted">
        <?= _f('Last ping on %s', _d($last_heartbeat_at, 'EEE d MMM YYYY, HH:mm:ss')) ?>
    </p>
<?php endif; ?>

<p class="paragraph--centered">
    <a href="" class="link--primary" data-turbolinks="false">
        <?= _('↻ Refresh the page') ?>
    </a>
</p>

<?php if ($alarms): ?>
    <h2 id="alarms"><?= _('Alarms') ?></h2>

    <ul class="list">
        <?php foreach ($alarms as $alarm): ?>
            <?= $this->include('alarms/_alarm.phtml', ['alarm' => $alarm, 'from' => url('show domain', ['id' => $domain->id]) . '#alarms']) ?>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>

<section class="section--danger">
    <h2><?= _('Danger zone 😈') ?></h2>

    <form
        method="post"
        action="<?= url('delete domain', ['id' => $domain->id]) ?>"
        data-controller="confirmation"
        data-action="confirmation#confirm"
        data-confirmation-message-value="<?= _('Are you sure that you want to stop to monitor this domain?') ?>"
    >
        <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />
        <button type="submit">
            <?= _('Stop monitoring this domain') ?>
        </button>
    </form>
</section>
