<li id="alarm-<?= $alarm->id ?>" class="list__item <?= $alarm->finished_at ? 'list__item--muted' : '' ?>">
    <?= $alarm->details ?>

    <br />

    <div class="list__footer">
        <div>
            <?php if ($alarm->domain_id): ?>
                <a
                    <?= $alarm->finished_at ? 'class="link--muted"' : '' ?>
                    href="<?= url('show domain', ['id' => $alarm->domain_id]) ?>#alarm-<?= $alarm->id ?>"
                    data-turbolinks="false"
                ><?= _d($alarm->created_at, '%F %T') ?></a>
            <?php else: ?>
                <a
                    <?= $alarm->finished_at ? 'class="link--muted"' : '' ?>
                    href="<?= url('show server', ['id' => $alarm->server_id]) ?>#alarm-<?= $alarm->id ?>"
                    data-turbolinks="false"
                ><?= _d($alarm->created_at, '%F %T') ?></a>
            <?php endif; ?>

            <?php if ($alarm->finished_at): ?>
                · <span title="<?= _d($alarm->finished_at, '%F %T') ?>"><?= _('finished') ?></span>
            <?php endif; ?>
        </div>

        <?php if (!$alarm->finished_at): ?>
            <form method="post" action="<?= url('finish alarm', ['id' => $alarm->id]) ?>">
                <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
                <input type="hidden" name="from" value="<?= $from ?>" />

                <button type="submit" class="button--ghost">
                    <?= _('Ignore') ?>
                </button>
            </form>
        <?php endif; ?>
    </div>
</li>
