<?php
    $this->layout('application.phtml', [
        'title' => _('Add a server to monitor'),
        'navigation_active' => 'servers',
    ]);
?>

<h1><?= _('Add a server to monitor') ?></h1>

<form method="post" action="<?= url('create server') ?>">
    <?php if ($error): ?>
        <p class="form__error">
            <?= $error ?>
        </p>
    <?php endif; ?>

    <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

    <div class="form-group <?= isset($errors['hostname']) ? 'form-group--invalid' : '' ?>">
        <label for="hostname">
            <?= _('Hostname') ?>
        </label>

        <input
            id="hostname"
            name="hostname"
            type="text"
            value="<?= $hostname ?>"
            required
            autofocus
        />

        <?php if (isset($errors['hostname'])): ?>
            <p class="form-group__error">
                <?= $errors['hostname'] ?>
            </p>
        <?php else: ?>
            <?php if (isset($errors['ipv4'])): ?>
                <p class="form-group__error">
                    <?= $errors['ipv4'] ?>
                </p>
            <?php endif; ?>

            <?php if (isset($errors['ipv6'])): ?>
                <p class="form-group__error">
                    <?= $errors['ipv6'] ?>
                </p>
            <?php endif; ?>
        <?php endif; ?>
    </div>

    <div class="form__actions">
        <button type="submit" class="button--primary">
            <?= _('Monitor the server') ?>
        </button>

        <a href="<?= url('servers') ?>">
            <?= _('Back to the servers') ?>
        </a>
    </div>
</form>
