<?php
    $this->layout('application.phtml', [
        'title' => _('Add a server to monitor'),
        'navigation_active' => 'servers',
    ]);
?>

<h1><?= _('Add a server to monitor') ?></h1>

<form method="post" action="<?= url('create server') ?>">
    <?php if ($form->isInvalid('@base')): ?>
        <p class="form__error">
            <?= $form->error('@base') ?>
        </p>
    <?php endif; ?>

    <div class="form-group <?= $form->isInvalid('hostname') ? 'form-group--invalid' : '' ?>">
        <label for="hostname">
            <?= _('Hostname') ?>
        </label>

        <input
            id="hostname"
            name="hostname"
            type="text"
            value="<?= $form->hostname ?>"
            required
            autofocus
        />

        <?php if ($form->isInvalid('hostname')): ?>
            <p class="form-group__error">
                <?= $form->error('hostname') ?>
            </p>
        <?php else: ?>
            <?php if ($form->isInvalid('ipv4')): ?>
                <p class="form-group__error">
                    <?= $form->error('ipv4') ?>
                </p>
            <?php endif; ?>

            <?php if ($form->isInvalid('ipv6')): ?>
                <p class="form-group__error">
                    <?= $form->error('ipv6') ?>
                </p>
            <?php endif; ?>
        <?php endif; ?>
    </div>

    <div class="form__actions">
        <button type="submit" class="button--primary">
            <?= _('Monitor the server') ?>
        </button>

        <a href="<?= url('servers') ?>">
            <?= _('Back to the servers') ?>
        </a>
    </div>

    <input type="hidden" name="csrf_token" value="<?= $form->csrfToken() ?>">
</form>
