<?php $this->layout('base.phtml', ['title' => _f('Server %s', $this->protect($server->hostname))]); ?>

<h1><?= $this->protect($server->hostname) ?></h1>

<ul>
    <li>IP v4&nbsp;: <?= $server->ipv4 ?></li>
    <li>IP v6&nbsp;: <?= $server->ipv6 ?></li>
</ul>

<p>
    <?= _f('Status: %s', _($server->status())) ?>
    <?php if ($metric): ?>
        /
        <?= _f('Last ping on %s', _d($metric->created_at, '%a %d %b %Y %H:%M:%S')) ?>
    <?php endif; ?>
</p>

<h2><?= _f('Server configuration') ?></h2>

<div id="server-conf" class="server-conf">
    <a class="server-conf__display" href="#server-conf">
        <?= _('Display') ?>
    </a>

    <a class="server-conf__hide" href="#">
        <?= _('Hide') ?>
    </a>

    <div class="server-conf__snippet">
        ENDPOINT=<?= url_full('create metrics') ?><br />
        AUTH_TOKEN=<?= $server->auth_token ?>
    </div>
</div>

<?php if ($metric && $server->status() === 'up'): ?>
    <h2><?= _('CPU') ?></h2>

    <ul>
        <?php foreach ($metric->cpuPercents() as $cpu_id => $percent): ?>
            <li>
                <?= _f('CPU%d', $cpu_id + 1) ?>: <?= $percent ?>&nbsp;%
            </li>
        <?php endforeach; ?>
    </ul>

    <h2><?= _('Memory') ?></h2>

    <p>
        <?= _f('%s used on %s', format_bytes($metric->memoryUsed()), format_bytes($metric->memoryTotal())) ?>
        (<?= format_number($metric->memoryUsedPercent()) ?>&nbsp;%)
    </p>

    <h2><?= _('Disks') ?></h2>

    <ul>
        <?php foreach ($metric->disks() as $disk): ?>
            <li>
                <?= $disk->name ?>:
                <?= _f('%s used on %s', format_bytes($metric->diskUsed($disk)), format_bytes($disk->total)) ?>
                (<?= format_number($metric->diskUsedPercent($disk)) ?>&nbsp;%)
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
