<?php
    if ($is_app_page) {
        $feed_url = url_full('page feed');
    } else {
        $feed_url = url_full('page feed', ['id' => $page->id]);
    }

    $this->layout('base.phtml', [
        'title' => $title,
        'feed' => [
            'url' => $feed_url,
            'title' => $this->protect($page->title),
        ],
    ]);
?>

<div class="layout layout--page">
    <main class="layout__content">
        <nav class="layout__back">
            <?php if ($is_app_page): ?>
                <a href="<?= url('home') ?>">
                    <?= $this->protect($page->title) ?>
                </a>
            <?php else: ?>
                <a href="<?= url('show page', ['id' => $page->id]) ?>">
                    <?= $this->protect($page->title) ?>
                </a>
            <?php endif; ?>
        </nav>

        <?= $this->safe('content') ?>
    </main>
</div>
