<?php $this->layout('base.phtml', ['title' => $title]); ?>

<div class="layout layout--application">
    <aside class="aside aside--layout">
        <nav class="aside__navigation">
            <a class="aside__link aside__link--home" href="<?= url('home') ?>">
                taust
            </a>

            <ul class="aside__group aside__group--grow">
                <li>
                    <a
                        class="aside__link <?= $navigation_active === 'dashboard' ? 'aside__link--active' : '' ?>"
                        href="<?= url('home') ?>"
                    >
                        <?= _('Dashboard') ?>
                    </a>
                </li>

                <li>
                    <a
                        class="aside__link <?= $navigation_active === 'domains' ? 'aside__link--active' : '' ?>"
                        href="<?= url('domains') ?>"
                    >
                        <?= _('Domains') ?>
                    </a>
                </li>

                <li>
                    <a
                        class="aside__link <?= $navigation_active === 'servers' ? 'aside__link--active' : '' ?>"
                        href="<?= url('servers') ?>"
                    >
                        <?= _('Servers') ?>
                    </a>
                </li>

                <li>
                    <a
                        class="aside__link <?= $navigation_active === 'alarms' ? 'aside__link--active' : '' ?>"
                        href="<?= url('alarms') ?>"
                    >
                        <?= _('Alarms') ?>
                    </a>
                </li>

                <li>
                    <a
                        class="aside__link <?= $navigation_active === 'pages' ? 'aside__link--active' : '' ?>"
                        href="<?= url('pages') ?>"
                    >
                        <?= _('Status pages') ?>
                    </a>
                </li>

                <li>
                    <a
                        class="aside__link <?= $navigation_active === 'user' ? 'aside__link--active' : '' ?>"
                        href="<?= url('user') ?>"
                    >
                        <?= _f('Profile (%s)', $this->protect($current_user->username)) ?>
                    </a>
                </li>
            </ul>

            <form method="post" action="<?= url('logout') ?>" class="aside__bottom">
                <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />
                <button type="submit" class="aside__button aside__button--logout">
                    <?= _('Logout') ?>
                </button>
            </form>
        </nav>
    </aside>

    <main class="layout__content">
        <?= $this->safe('content') ?>
    </main>
</div>
