<!DOCTYPE html>
<html lang="<?= locale_to_bcp_47($current_locale) ?>">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="initial-scale=1.0" />
        <link rel="shortcut icon" href="<?= url_public('favicon.ico') ?>">

        <link rel="stylesheet" href="<?= url_static('stylesheets/application.css') ?>" data-turbolinks-track="reload">
        <?php if (isset($custom_style_url)): ?>
            <link rel="stylesheet" href="<?= $custom_style_url ?>" data-turbolinks-track="reload">
        <?php endif; ?>

        <script src="<?= url_static('javascripts/turbolinks.js') ?>" defer data-turbolinks-track="reload"></script>

        <?php if ($current_user): ?>
            <script type="module" src="<?= url_static('javascripts/stimulus.3.0.1.js') ?>" defer data-turbolinks-track="reload"></script>
            <script type="module" src="<?= url_static('javascripts/application.js') ?>" defer data-turbolinks-track="reload"></script>
        <?php endif; ?>

        <?php if (isset($feed)): ?>
            <link href="<?= $feed['url'] ?>" type="application/atom+xml" rel="alternate" title="<?= $feed['title'] ?>" />
        <?php endif; ?>

        <title><?= $title ?></title>
    </head>

    <body>
        <?= $this->safe('content') ?>
    </body>
</html>
