<!DOCTYPE html>
<html lang="en-GB">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="initial-scale=1.0" />
        <link rel="shortcut icon" href="<?= url_public('favicon.ico') ?>">

        <link rel="stylesheet" href="<?= url_static('stylesheets/application.css') ?>" data-turbolinks-track="reload">

        <script src="<?= url_static('javascripts/turbolinks.js') ?>" defer data-turbolinks-track="reload"></script>

        <title><?= $title ?> · taust</title>
    </head>

    <body>
        <?= $this->safe('content') ?>
    </body>
</html>
