<?php $this->layout('base.phtml', ['title' => $title]); ?>

<div class="layout layout--page">
    <main class="layout__content">
        <h1 class="layout__title">
            <?php if ($current_user): ?>
                <a href="<?= url('edit page', ['id' => $page->id]) ?>">
                    <?= $title ?>
                </a>
            <?php else: ?>
                <?= $title ?>
            <?php endif; ?>
        </h1>

        <?= $this->safe('content') ?>
    </main>
</div>
