<?php
    if ($is_app_page) {
        $feed_url = url_full('page feed');
    } else {
        $feed_url = url_full('page feed', ['id' => $page->id]);
    }

    if ($page->style && $is_app_page) {
        $custom_style_url = url('page style');
    } elseif ($page->style) {
        $custom_style_url = url('page style', ['id' => $page->id]);
    } else {
        $custom_style_url = null;
    }

    $this->layout('base.phtml', [
        'title' => $title,
        'feed' => [
            'url' => $feed_url,
            'title' => $this->protect($page->title),
        ],
        'custom_style_url' => $custom_style_url,
    ]);
?>

<div class="layout layout--page">
    <main class="layout__content">
        <?php if ($current_user): ?>
            <div class="header">
                <h1 class="header__item--extend">
                    <?= $title ?>
                </h1>

                <a class="link--primary" href="<?= url('edit page', ['id' => $page->id]) ?>">
                    <?= _('Edit the page') ?>
                </a>
            </div>
        <?php else: ?>
            <h1 class="layout__title">
                <?= $title ?>
            </h1>
        <?php endif; ?>

        <?= $this->safe('content') ?>
    </main>
</div>
