<?php
    if ($is_app_page) {
        $feed_url = url_full('page feed');
    } else {
        $feed_url = url_full('page feed', ['id' => $page->id]);
    }

    $this->layout('base.phtml', [
        'title' => $title,
        'feed' => [
            'url' => $feed_url,
            'title' => $this->protect($page->title),
        ],
    ]);
?>

<div class="layout layout--page">
    <main class="layout__content">
        <h1 class="layout__title">
            <?php if ($current_user): ?>
                <a href="<?= url('edit page', ['id' => $page->id]) ?>">
                    <?= $title ?>
                </a>
            <?php else: ?>
                <?= $title ?>
            <?php endif; ?>
        </h1>

        <?= $this->safe('content') ?>
    </main>
</div>
