<?php
    $this->layout('application.phtml', [
        'title' => _f('Page %s', $this->protect($page->title)),
        'navigation_active' => 'pages',
    ]);
?>

<div class="header">
    <h1 class="header__item--extend"><?= $this->protect($page->title) ?></h1>

    <a class="link--primary" href="<?= url('show page', ['id' => $page->id]) ?>">
        <?= _('Show the page') ?>
    </a>
</div>

<form method="post" action="<?= url('update page', ['id' => $page->id]) ?>">
    <?php if ($form->isInvalid('@base')): ?>
        <p class="form__error">
            <?= $form->error('@base') ?>
        </p>
    <?php endif; ?>

    <div class="form-group <?= $form->isInvalid('domain_ids') ? 'form-group--invalid' : '' ?>">
        <label for="domain-ids">
            <?= _('Domains (optional)') ?>
        </label>

        <select id="domain-ids" name="domain_ids[]" multiple>
            <?php foreach ($form->domains() as $domain): ?>
                <option <?= $form->isDomainSelected($domain) ? 'selected' : '' ?> value="<?= $domain->id ?>">
                    <?= protect($domain->id) ?>
                </option>
            <?php endforeach; ?>
        </select>

        <?php if ($form->isInvalid('domain_ids')): ?>
            <p class="form-group__error">
                <?= $form->error('domain_ids') ?>
            </p>
        <?php endif; ?>
    </div>

    <div class="form-group <?= $form->isInvalid('server_ids') ? 'form-group--invalid' : '' ?>">
        <label for="server-ids">
            <?= _('Servers (optional)') ?>
        </label>

        <select id="server-ids" name="server_ids[]" multiple>
            <?php foreach ($form->servers() as $server): ?>
                <option <?= $form->isServerSelected($server) ? 'selected' : '' ?> value="<?= $server->id ?>">
                    <?= protect($server->hostname) ?>
                </option>
            <?php endforeach; ?>
        </select>

        <?php if ($form->isInvalid('server_ids')): ?>
            <p class="form-group__error">
                <?= $form->error('server_ids') ?>
            </p>
        <?php endif; ?>
    </div>

    <div class="form-group <?= $form->isInvalid('hostname') ? 'form-group--invalid' : '' ?>">
        <label for="hostname">
            <?= _('Hostname (optional)') ?>
        </label>

        <div class="form-group__stack">
            <input
                id="hostname"
                name="hostname"
                type="text"
                value="<?= $form->hostname ?>"
            />

            <?php if ($form->hostname): ?>
                <a class="link--primary" target="_blank" rel="noopener noreferrer" href="https://<?= $form->hostname ?>">
                    <?= _('open') ?>
                </a>
            <?php endif; ?>
        </div>

        <?php if ($form->isInvalid('hostname')): ?>
            <p class="form-group__error">
                <?= $form->error('hostname') ?>
            </p>
        <?php endif; ?>
    </div>

    <div class="form-group <?= $form->isInvalid('style') ? 'form-group--invalid' : '' ?>">
        <label for="style">
            <?= _('Custom style (optional)') ?>
        </label>

        <textarea id="style" name="style" spellcheck="false"><?= $form->style ?></textarea>

        <?php if ($form->isInvalid('style')): ?>
            <p class="form-group__error">
                <?= $form->error('style') ?>
            </p>
        <?php endif; ?>
    </div>

    <div class="form-group <?= $form->isInvalid('locale') ? 'form-group--invalid' : '' ?>">
        <label for="locale">
            <?= _('Page language') ?>
        </label>

        <select id="locale" name="locale" required>
            <option <?= $form->locale === 'auto' ? 'selected' : '' ?> value="auto">
                <?= _('Autodetected') ?>
            </option>

            <option <?= $form->locale === 'en_GB' ? 'selected' : '' ?> value="en_GB">
                English
            </option>

            <option <?= $form->locale === 'fr_FR' ? 'selected' : '' ?> value="fr_FR">
                Français
            </option>
        </select>

        <?php if ($form->isInvalid('locale')): ?>
            <p class="form-group__error">
                <?= $form->error('locale') ?>
            </p>
        <?php endif; ?>
    </div>

    <div class="form__actions">
        <button type="submit" class="button--primary">
            <?= _('Save changes') ?>
        </button>
    </div>

    <input type="hidden" name="csrf_token" value="<?= $form->csrfToken() ?>" />
</form>

<section class="section--danger">
    <h2><?= _('Danger zone 😈') ?></h2>

    <form
        method="post"
        action="<?= url('delete page', ['id' => $page->id]) ?>"
        data-controller="confirmation"
        data-action="confirmation#confirm"
        data-confirmation-message-value="<?= _('Are you sure that you want to delete this page?') ?>"
    >
        <input type="hidden" name="csrf_token" value="<?= $base_form->csrfToken() ?>" />
        <button type="submit">
            <?= _('Delete this status page') ?>
        </button>
    </form>
</section>
