<?php
    $this->layout('application.phtml', [
        'title' => _f('Page %s', $this->protect($page->title)),
        'navigation_active' => 'pages',
    ]);
?>

<h1>
    <a href="<?= url('show page', ['id' => $page->id]) ?>">
        <?= $this->protect($page->title) ?>
    </a>
</h1>

<form method="post" action="<?= url('update page', ['id' => $page->id]) ?>">
    <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

    <div class="form-group <?= isset($errors['domain_ids']) ? 'form-group--invalid' : '' ?>">
        <label for="domain-ids">
            <?= _('Domains (optional)') ?>
        </label>

        <select id="domain-ids" name="domain_ids[]" multiple>
            <?php foreach ($domains as $domain): ?>
                <option <?= in_array($domain->id, $domain_ids) ? 'selected' : '' ?> value="<?= $domain->id ?>">
                    <?= protect($domain->id) ?>
                </option>
            <?php endforeach; ?>
        </select>

        <?php if (isset($errors['domain_ids'])): ?>
            <p class="form-group__error">
                <?= $errors['domain_ids'] ?>
            </p>
        <?php endif; ?>
    </div>

    <div class="form-group <?= isset($errors['server_ids']) ? 'form-group--invalid' : '' ?>">
        <label for="server-ids">
            <?= _('Servers (optional)') ?>
        </label>

        <select id="server-ids" name="server_ids[]" multiple>
            <?php foreach ($servers as $server): ?>
                <option <?= in_array($server->id, $server_ids) ? 'selected' : '' ?> value="<?= $server->id ?>">
                    <?= protect($server->hostname) ?>
                </option>
            <?php endforeach; ?>
        </select>

        <?php if (isset($errors['server_ids'])): ?>
            <p class="form-group__error">
                <?= $errors['server_ids'] ?>
            </p>
        <?php endif; ?>
    </div>

    <div class="form-group <?= isset($errors['hostname']) ? 'form-group--invalid' : '' ?>">
        <label for="hostname">
            <?= _('Hostname (optional)') ?>
        </label>

        <div class="form-group__stack">
            <input
                id="hostname"
                name="hostname"
                type="text"
                value="<?= $hostname ?>"
            />

            <?php if ($hostname): ?>
                <a class="link--primary" target="_blank" rel="noopener noreferrer" href="<?= $hostname ?>">
                    <?= _('open') ?>
                </a>
            <?php endif; ?>
        </div>

        <?php if (isset($errors['hostname'])): ?>
            <p class="form-group__error">
                <?= $errors['hostname'] ?>
            </p>
        <?php endif; ?>
    </div>

    <div class="form-group <?= isset($errors['style']) ? 'form-group--invalid' : '' ?>">
        <label for="style">
            <?= _('Custom style (optional)') ?>
        </label>

        <textarea id="style" name="style" spellcheck="false"><?= $style ?></textarea>

        <?php if (isset($errors['style'])): ?>
            <p class="form-group__error">
                <?= $errors['style'] ?>
            </p>
        <?php endif; ?>
    </div>

    <div class="form__actions">
        <button type="submit" class="button--primary">
            <?= _('Save changes') ?>
        </button>
    </div>
</form>

<section class="section--danger">
    <h2><?= _('Danger zone 😈') ?></h2>

    <form
        method="post"
        action="<?= url('delete page', ['id' => $page->id]) ?>"
        data-controller="confirmation"
        data-action="confirmation#confirm"
        data-confirmation-message-value="<?= _('Are you sure that you want to delete this page?') ?>"
    >
        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
        <button type="submit">
            <?= _('Delete this status page') ?>
        </button>
    </form>
</section>
