<?php
    $this->layout('application.phtml', [
        'title' => _('Create a status page'),
        'navigation_active' => 'pages',
    ]);
?>

<h1><?= _('Create a status page') ?></h1>

<form method="post" action="<?= url('create page') ?>">
    <?php if ($form->isInvalid('@base')): ?>
        <p class="form__error">
            <?= $form->error('@base') ?>
        </p>
    <?php endif; ?>

    <div class="form-group <?= $form->isInvalid('title') ? 'form-group--invalid' : '' ?>">
        <label for="title">
            <?= _('Title') ?>
        </label>

        <input
            id="title"
            name="title"
            type="text"
            value="<?= $form->title ?>"
            required
            autofocus
        />

        <?php if ($form->isInvalid('title')): ?>
            <p class="form-group__error">
                <?= $form->error('title') ?>
            </p>
        <?php endif; ?>
    </div>

    <div class="form__actions">
        <button type="submit" class="button--primary">
            <?= _('Create the page') ?>
        </button>

        <a href="<?= url('pages') ?>">
            <?= _('Back to the pages') ?>
        </a>
    </div>

    <input type="hidden" name="csrf_token" value="<?= $form->csrfToken() ?>" />
</form>
