<?php
    $this->layout('page.phtml', [
        'title' => $this->protect($page->title),
        'page' => $page,
    ]);
?>

<?php if ($domains): ?>
    <h2><?= _('Domains') ?></h2>

    <ul class="list">
        <?php foreach ($domains as $domain): ?>
            <li class="list__item list__item--row">
                <a target="_blank" rel="noopener noreferrer" href="https://<?= $this->protect($domain->id) ?>">
                    <?= $this->protect($domain->id) ?>
                </a>

                <?php $status = $domain->status(); ?>
                <?php if ($status === 'up'): ?>
                    <span class="text--success">
                        <?= _('up 😊') ?>
                    </span>
                <?php elseif ($status === 'down'): ?>
                    <span class="text--alert">
                        <strong><?= _('down 😫') ?></strong>
                    </span>
                <?php else: ?>
                    <span class="text--warning">
                        <strong><?= _('unknown 😵') ?></strong>
                    </span>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>

<?php if ($servers): ?>
    <h2><?= _('Servers') ?></h2>
    <ul class="list">
        <?php foreach ($servers as $server): ?>
            <li class="list__item list__item--row">
                <?= $this->protect($server->hostname) ?>

                <?php $status = $server->status(); ?>
                <?php if ($status === 'up'): ?>
                    <span class="text--success">
                        <?= _('up 😊') ?>
                    </span>
                <?php elseif ($status === 'down'): ?>
                    <span class="text--alert">
                        <strong><?= _('down 😫') ?></strong>
                    </span>
                <?php else: ?>
                    <span class="text--warning">
                        <strong><?= _('unknown 😵') ?></strong>
                    </span>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>

<section class="posts">
    <?php if ($current_user): ?>
        <details class="form__displayer" <?= ($error || $errors) ? 'open' : '' ?>>
            <summary><?= _('Publish an announcement') ?></summary>

            <form method="post" action="<?= url('create announcement', ['id' => $page->id]) ?>">
                <?php if ($error): ?>
                    <p class="form__error">
                        <?= $error ?>
                    </p>
                <?php endif; ?>

                <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />

                <div class="form-group <?= isset($errors['type']) ? 'form-group--invalid' : '' ?>">
                    <label for="type">
                        <?= _('Type') ?>
                    </label>

                    <select id="type" name="type" required>
                        <option <?= $type === 'maintenance' ? 'selected' : '' ?> value="maintenance">
                            <?= _('🔧 Maintenance') ?>
                        </option>

                        <option <?= $type === 'incident' ? 'selected' : '' ?> value="incident">
                            <?= _('🔥 Incident') ?>
                        </option>
                    </select>

                    <?php if (isset($errors['type'])): ?>
                        <p class="form-group__error">
                            <?= $errors['type'] ?>
                        </p>
                    <?php endif; ?>
                </div>

                <div class="form-group <?= isset($errors['planned_at']) ? 'form-group--invalid' : '' ?>">
                    <label for="planned-at">
                        <?= _('Date') ?>
                    </label>

                    <input
                        id="planned-at"
                        name="planned_at"
                        type="datetime-local"
                        value="<?= _d($planned_at, "YYYY-MM-dd'T'HH:mm") ?>"
                        required
                    />

                    <?php if (isset($errors['planned_at'])): ?>
                        <p class="form-group__error">
                            <?= $errors['planned_at'] ?>
                        </p>
                    <?php endif; ?>
                </div>

                <div class="form-group <?= isset($errors['title']) ? 'form-group--invalid' : '' ?>">
                    <label for="title">
                        <?= _('Title') ?>
                    </label>

                    <input
                        id="title"
                        name="title"
                        type="text"
                        value="<?= $title ?>"
                        required
                    />

                    <?php if (isset($errors['title'])): ?>
                        <p class="form-group__error">
                            <?= $errors['title'] ?>
                        </p>
                    <?php endif; ?>
                </div>

                <div class="form-group <?= isset($errors['content']) ? 'form-group--invalid' : '' ?>">
                    <label for="content">
                        <?= _('Content') ?>
                    </label>

                    <textarea
                        id="content"
                        name="content"
                        required
                    ><?= $content ?></textarea>

                    <?php if (isset($errors['content'])): ?>
                        <p class="form-group__error">
                            <?= $errors['content'] ?>
                        </p>
                    <?php endif; ?>
                </div>

                <div class="form__actions">
                    <button type="submit" class="button--primary">
                        <?= _('Publish announcement') ?>
                    </button>
                </div>
            </form>
        </details>
    <?php endif; ?>

    <?php if (isset($announcements_by_days['future'])): ?>
        <h2 class="posts__day"><?= _('Planned maintenance') ?></h2>

        <?php foreach ($announcements_by_days['future'] as $announcement): ?>
            <?= $this->include('pages/announcements/_announcement.phtml', ['announcement' => $announcement]) ?>
        <?php endforeach; ?>
    <?php endif; ?>

    <?php $days_iterator = \Minz\Time::relative('today'); ?>
    <?php $one_week = \Minz\Time::relative('today -1 week'); ?>
    <?php while ($days_iterator > $one_week): ?>
        <?php $day = $days_iterator->format('Y-m-d'); ?>

        <h2 class="posts__day"><?= _d($days_iterator) ?></h2>

        <?php if (isset($announcements_by_days[$day])): ?>
            <?php foreach ($announcements_by_days[$day] as $announcement): ?>
                <?= $this->include('pages/announcements/_announcement.phtml', ['announcement' => $announcement]) ?>
            <?php endforeach; ?>
        <?php else: ?>
            <article class="post post--placeholder">
                <p>
                    <?= _('No incidents reported.') ?>
                </p>
            </article>
        <?php endif; ?>

        <?php $days_iterator = $days_iterator->modify('-1 day'); ?>
    <?php endwhile; ?>

    <?php if ($is_app_page): ?>
        <a class="posts__history" href="<?= url('page announcements') ?>">
            <?= _('Announcements history') ?>
        </a>
    <?php else: ?>
        <a class="posts__history" href="<?= url('page announcements', ['id' => $page->id]) ?>">
            <?= _('Announcements history') ?>
        </a>
    <?php endif; ?>
</section>
