<?php
    $this->layout('page.phtml', [
        'title' => $this->protect($page->title),
        'page' => $page,
    ]);
?>

<?php $domains = $page->domains(); ?>
<?php if ($domains): ?>
    <h2><?= _('Domains') ?></h2>

    <ul class="list">
        <?php foreach ($domains as $domain): ?>
            <li class="list__item list__item--row">
                <a target="_blank" rel="noopener noreferrer" href="https://<?= $this->protect($domain->id) ?>">
                    <?= $this->protect($domain->id) ?>
                </a>

                <?php $status = $domain->status(); ?>
                <?php if ($status === 'up'): ?>
                    <span class="text--success">
                        <?= _('up 😊') ?>
                    </span>
                <?php elseif ($status === 'down'): ?>
                    <span class="text--alert">
                        <strong><?= _('down 😫') ?></strong>
                    </span>
                <?php else: ?>
                    <span class="text--warning">
                        <strong><?= _('unknown 😵') ?></strong>
                    </span>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>

<?php $servers = $page->servers(); ?>
<?php if ($servers): ?>
    <h2><?= _('Servers') ?></h2>

    <ul class="list">
        <?php foreach ($servers as $server): ?>
            <li class="list__item list__item--row">
                <?= $this->protect($server->hostname) ?>

                <?php $status = $server->status(); ?>
                <?php if ($status === 'up'): ?>
                    <span class="text--success">
                        <?= _('up 😊') ?>
                    </span>
                <?php elseif ($status === 'down'): ?>
                    <span class="text--alert">
                        <strong><?= _('down 😫') ?></strong>
                    </span>
                <?php else: ?>
                    <span class="text--warning">
                        <strong><?= _('unknown 😵') ?></strong>
                    </span>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>

<section class="posts">
    <?php if ($current_user): ?>
        <details class="form__displayer" <?= $announcement_form->isInvalid() ? 'open' : '' ?>>
            <summary><?= _('Publish an announcement') ?></summary>

            <?= $this->include('announcements/_form.phtml', [
                'form' => $announcement_form,
                'action' => url('create announcement', ['id' => $page->id]),
                'submit' => _('Publish announcement'),
            ]) ?>
        </details>
    <?php endif; ?>

    <?php $announcements_by_days = $page->weekAnnouncements(); ?>
    <?php if (isset($announcements_by_days['future'])): ?>
        <h2 class="posts__day"><?= _('Planned maintenance') ?></h2>

        <?php foreach ($announcements_by_days['future'] as $announcement): ?>
            <?= $this->include('announcements/_announcement.phtml', ['announcement' => $announcement]) ?>
        <?php endforeach; ?>
    <?php endif; ?>

    <?php $days_iterator = \Minz\Time::relative('today'); ?>
    <?php $one_week = \Minz\Time::relative('today -1 week'); ?>
    <?php while ($days_iterator > $one_week): ?>
        <?php $day = $days_iterator->format('Y-m-d'); ?>

        <h2 class="posts__day"><?= _d($days_iterator) ?></h2>

        <?php if (isset($announcements_by_days[$day])): ?>
            <?php foreach ($announcements_by_days[$day] as $announcement): ?>
                <?= $this->include('announcements/_announcement.phtml', ['announcement' => $announcement]) ?>
            <?php endforeach; ?>
        <?php else: ?>
            <article class="post post--placeholder">
                <p>
                    <?= _('No incidents reported.') ?>
                </p>
            </article>
        <?php endif; ?>

        <?php $days_iterator = $days_iterator->modify('-1 day'); ?>
    <?php endwhile; ?>

    <?php if ($is_app_page): ?>
        <a class="posts__history" href="<?= url('page announcements') ?>">
            <?= _('Announcements history') ?>
        </a>
    <?php else: ?>
        <a class="posts__history" href="<?= url('page announcements', ['id' => $page->id]) ?>">
            <?= _('Announcements history') ?>
        </a>
    <?php endif; ?>
</section>
