<?php $this->layout('base.phtml', ['title' => _('Dashboard')]); ?>

<a href="<?= url('new domain') ?>">
    <?= _('Add a new domain') ?>
</a>

<ul>
    <?php foreach ($domains as $domain): ?>
    <li>
        <a href="<?= url('show domain', ['id' => $domain->id]) ?>">
            <?= $this->protect($domain->id) ?>
        </a>
        (<?= _($domain->status()) ?>)
    </li>
    <?php endforeach; ?>
</ul>

<a href="<?= url('new server') ?>">
    <?= _('Add a new server') ?>
</a>

<ul>
    <?php foreach ($servers as $server): ?>
        <li>
            <a href="<?= url('show server', ['id' => $server->id]) ?>">
                <?= $this->protect($server->hostname) ?>
            </a>
        </li>
    <?php endforeach; ?>
</ul>
