version: '3'

services:
    php:
        image: taust_php:dev
        build: .
        restart: unless-stopped
        ports:
            - "9000:9000"
        volumes:
            - ..:/var/www/html:z
        user: $USER
        links:
            - database

    job_worker:
        image: taust_php:dev
        build: .
        restart: unless-stopped
        command: php cli jobs watch
        volumes:
            - ..:/var/www/html:z
        user: $USER
        links:
            - database

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ..:/var/www/html:z
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:z
        links:
            - php

    database:
        image: postgres:12-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"

volumes:
    composer: {}
