<?php
    $page = $announcement->page();

    $this->layout('announcement.phtml', [
        'title' => _f('Edit %s', $this->protect($announcement->title)),
        'navigation_active' => 'pages',
        'page' => $page,
    ]);
?>

<?= $this->include('announcements/_form.phtml', [
    'form' => $form,
    'action' => url('update announcement', ['id' => $announcement->id]),
    'submit' => _('Save changes'),
]) ?>
