<?php
    $this->layout('application.phtml', [
        'title' => _f('Page %s', $this->protect($page->title)),
        'navigation_active' => 'pages',
    ]);
?>

<h1>
    <a target="_blank" rel="noopener noreferrer" href="<?= url('show page', ['id' => $page->id]) ?>">
        <?= $this->protect($page->title) ?>
    </a>
</h1>

<nav class="subnavigation">
    <ul class="subnavigation__container">
        <li class="subnavigation__item">
            <a
                class="subnavigation__link subnavigation__link--active"
                href="<?= url('announcements', ['id' => $page->id]) ?>"
            >
                <?= _('Announcements') ?>
            </a>
        </li>

        <li class="subnavigation__item">
            <a
                class="subnavigation__link"
                href="<?= url('edit page', ['id' => $page->id]) ?>"
            >
                <?= _('Configuration') ?>
            </a>
        </li>
    </ul>
</nav>

<details class="form__displayer">
    <summary>Publish an announcement</summary>

    <form method="post" action="<?= url('create announcement', ['id' => $page->id]) ?>">
        <?php if ($error): ?>
            <p class="form__error">
                <?= $error ?>
            </p>
        <?php endif; ?>

        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

        <div class="form-group <?= isset($errors['type']) ? 'form-group--invalid' : '' ?>">
            <label for="type">
                <?= _('Type') ?>
            </label>

            <select id="type" name="type" required>
                <option <?= $type === 'maintenance' ? 'selected' : '' ?> value="maintenance">
                    <?= _('🔧 Maintenance') ?>
                </option>

                <option <?= $type === 'incident' ? 'selected' : '' ?> value="incident">
                    <?= _('🔥 Incident') ?>
                </option>
            </select>

            <?php if (isset($errors['type'])): ?>
                <p class="form-group__error">
                    <?= $errors['type'] ?>
                </p>
            <?php endif; ?>
        </div>

        <div class="form-group <?= isset($errors['planned_at']) ? 'form-group--invalid' : '' ?>">
            <label for="planned-at">
                <?= _('Date') ?>
            </label>

            <input
                id="planned-at"
                name="planned_at"
                type="datetime-local"
                value="<?= _d($planned_at, '%FT%H:%M') ?>"
                required
            />

            <?php if (isset($errors['planned_at'])): ?>
                <p class="form-group__error">
                    <?= $errors['planned_at'] ?>
                </p>
            <?php endif; ?>
        </div>

        <div class="form-group <?= isset($errors['title']) ? 'form-group--invalid' : '' ?>">
            <label for="title">
                <?= _('Title') ?>
            </label>

            <input
                id="title"
                name="title"
                type="text"
                value="<?= $title ?>"
                required
            />

            <?php if (isset($errors['title'])): ?>
                <p class="form-group__error">
                    <?= $errors['title'] ?>
                </p>
            <?php endif; ?>
        </div>

        <div class="form-group <?= isset($errors['content']) ? 'form-group--invalid' : '' ?>">
            <label for="content">
                <?= _('Content') ?>
            </label>

            <textarea
                id="content"
                name="content"
                required
            ><?= $content ?></textarea>

            <?php if (isset($errors['content'])): ?>
                <p class="form-group__error">
                    <?= $errors['content'] ?>
                </p>
            <?php endif; ?>
        </div>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Publish announcement') ?>
            </button>
        </div>
    </form>
</details>

<section class="posts">
    <?php foreach ($announcements as $announcement): ?>
        <?= $this->include('pages/announcements/_announcement.phtml', ['announcement' => $announcement]) ?>
    <?php endforeach; ?>
</section>
