<?php $this->layout('centered.phtml', ['title' => _('Log in taust')]); ?>

<form method="post" action="<?= url('create session') ?>">
    <?php if ($form->isInvalid('@base')): ?>
        <p class="form__error">
            <?= $form->error('@base') ?>
        </p>
    <?php endif; ?>

    <div class="form-group">
        <label for="username">
            <?= _('Username') ?>
        </label>

        <input
            id="username"
            name="username"
            type="text"
            value="<?= $form->username ?>"
            required
            autofocus
        />
    </div>

    <div class="form-group">
        <label for="password">
            <?= _('Password') ?>
        </label>

        <input
            id="password"
            name="password"
            type="password"
            required
        />
    </div>

    <div class="form__actions">
        <button type="submit" class="button--primary">
            <?= _('Login') ?>
        </button>
    </div>

    <input type="hidden" name="csrf_token" value="<?= $form->csrfToken() ?>">
</form>
