<?php
    $this->layout('application.phtml', [
        'title' => _('Your profile'),
        'navigation_active' => 'user',
    ]);
?>

<h1>
    <?= _f('Your profile (%s)', $this->protect($current_user->username)) ?>
</h1>

<form method="post" action="<?= url('update user') ?>">
    <?php if ($form->isInvalid('@base')): ?>
        <p class="form__error">
            <?= $form->error('@base') ?>
        </p>
    <?php endif; ?>

    <p>
        <?= _('You’ll receive alarms notifications by setting these information.') ?>
    </p>

    <?php if ($error): ?>
        <p class="form__error">
            <?= $error ?>
        </p>
    <?php endif; ?>

    <div class="form-group <?= $form->isInvalid('email') ? 'form-group--invalid' : '' ?>">
        <label for="email">
            <?= _('Email address') ?>
        </label>

        <input
            id="email"
            name="email"
            type="email"
            value="<?= $form->email ?>"
        />

        <?php if ($form->isInvalid('email')): ?>
            <p class="form-group__error">
                <?= $form->error('email') ?>
            </p>
        <?php endif; ?>
    </div>

    <div class="form-group <?= $form->isInvalid('free_mobile_login') ? 'form-group--invalid' : '' ?>">
        <label for="free_mobile_login">
            <?= _('Free mobile login') ?>
        </label>

        <input
            id="free_mobile_login"
            name="free_mobile_login"
            type="text"
            value="<?= $form->free_mobile_login ?>"
        />

        <?php if ($form->isInvalid('free_mobile_login')): ?>
            <p class="form-group__error">
                <?= $form->error('free_mobile_login') ?>
            </p>
        <?php endif; ?>
    </div>

    <div class="form-group <?= $form->isInvalid('free_mobile_key') ? 'form-group--invalid' : '' ?>">
        <label for="free_mobile_key">
            <?= _('Free mobile key') ?>
        </label>

        <input
            id="free_mobile_key"
            name="free_mobile_key"
            type="password"
            value="<?= $form->free_mobile_key ?>"
        />

        <?php if ($form->isInvalid('free_mobile_key')): ?>
            <p class="form-group__error">
                <?= $form->error('free_mobile_key') ?>
            </p>
        <?php endif; ?>
    </div>

    <div class="form__actions">
        <button type="submit" class="button--primary">
            <?= _('Update your profile') ?>
        </button>

        <a href="<?= url('home') ?>">
            <?= _('Back to the dashboard') ?>
        </a>
    </div>

    <input type="hidden" name="csrf_token" value="<?= $form->csrfToken() ?>" />
</form>
